name: heagy-2021-tle-casing
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - discretize=0.7.3
  - jupyter
  - matplotlib=3.4.3
  - mkl
  - numpy
  - pydiso=0.0.3
  - pymatsolver=0.2.0
  - python=3.8.12
  - scipy=1.5.3
  - simpeg=0.16.0
  - pip:
    - casingSimulations==0.2.1
