name: heagy-2021-tle-casing
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - discretize
  - jupyter
  - matplotlib
  - mkl
  - numpy
  - pydiso=0.0.3
  - pymatsolver=0.2.0
  - python=3.8.12
  - scipy=1.5.3
  - simpeg=0.17.0
  - pip:
    - casingSimulations=0.2.0
